# Generated by Django 5.2.4 on 2025-07-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=100, verbose_name='Şehir')),
                ('ilce', models.CharField(max_length=100, verbose_name='İlçe')),
                ('mahalle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('ortalama_kira', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ortalama Kira')),
                ('son_artis_yuzdesi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Son Artış Yüzdesi')),
            ],
            options={
                'verbose_name': 'Bölge',
                'verbose_name_plural': 'Bölgeler',
                'unique_together': {('sehir', 'ilce', 'mahalle')},
            },
        ),
        migrations.CreateModel(
            name='KiraIlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kira Fiyatı')),
                ('metrekare', models.IntegerField(verbose_name='Metrekare')),
                ('oda_sayisi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oda Sayısı')),
                ('binanin_yasi', models.IntegerField(blank=True, null=True, verbose_name='Binanın Yaşı')),
                ('esyalimi', models.BooleanField(default=False, verbose_name='Eşyalı mı?')),
                ('isinma_tipi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Isınma Tipi')),
                ('ilan_url', models.URLField(max_length=500, unique=True, verbose_name="İlan URL'si")),
                ('ilan_kaynagi', models.CharField(max_length=100, verbose_name='İlan Kaynağı')),
                ('ilan_tarihi', models.DateField(verbose_name='İlan Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('veri_cekme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Veri Çekme Tarihi')),
                ('bolge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kira_ilanlari', to='emlak.bolge', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'Kira İlanı',
                'verbose_name_plural': 'Kira İlanları',
                'ordering': ['-ilan_tarihi'],
            },
        ),
    ]
